tests/yaml/S_PS_UTIL_0009.yml, tests/yaml/S_PS_UTIL_0015.yml, tests/yaml/S_PS_UTIL_0021.yml, tests/yaml/S_PS_UTIL_0023.yml, tests/yaml/S_PS_UTIL_0026.yml
=> Updated yamls 

tests/yaml/S_WF_001.yml, tests/yaml/S_WF_002.yml, tests/yaml/S_WF_008.yml
These yamls will be used to test the run status from the step statuses.
=> Adding yamls for step workflow

tests/yaml/S_Bash_0538.yml, tests/yaml/S_Bash_0539.yml, tests/yaml/S_Bash_0540.yml, tests/yaml/S_Bash_0541.yml, tests/yaml/S_Bash_0542.yml, tests/yaml/S_Bash_0543.yml, tests/yaml/S_Bash_0544.yml, tests/yaml/S_CreateReleaseBundle_0001.yml, tests/yaml/S_HelmDeploy_0001.yml, tests/yaml/S_Matrix_0026.yml, tests/yaml/S_PS_Generic_0062.yml, tests/yaml/S_PostMatrix_0022.yml, tests/yaml/S_PreMatrix_0016.yml, tests/yaml/S_PromoteBuild_0001.yml, tests/yaml/S_PublishBuildInfo_0001.yml, tests/yaml/S_SignReleaseBundle_0001.yml, tests/yaml/S_XrayScan_0001.yml
Adds YML files for newVersionOnly tests.
=> Adds new newVersionOnly test files.

tests/yaml/S_WF_001.yml, tests/yaml/S_WF_002.yml, tests/yaml/S_WF_003.yml, tests/yaml/S_WF_004.yml, tests/yaml/S_WF_005.yml, tests/yaml/S_WF_006.yml, tests/yaml/S_WF_007.yml, tests/yaml/S_WF_008.yml, tests/yaml/S_WF_009.yml
Added new test cases for the step workflow automation yamls
=> Step workflow file changes

tests/yaml/S_WF_010.yml, tests/yaml/S_WF_011.yml, tests/yaml/S_WF_012.yml, tests/yaml/S_WF_013.yml, tests/yaml/S_WF_014.yml, tests/yaml/S_WF_015.yml
Renumbering and removed `newVersionOnly` from one step in `S_WF_011`.
=> PIPE-3616 - Renumbers newVersionOnly YMLs.

tests/yaml/api_runs.yml
https://www.jfrog.com/jira/browse/PIPE-3303
=> Add input resources and output resources to the step

tests/yaml/S_Bash_Util_0013.yml, tests/yaml/S_Bash_Util_0014.yml, tests/yaml/S_Bash_Util_0015.yml, tests/yaml/S_Bash_Util_0016.yml, tests/yaml/S_Bash_Util_0017.yml, tests/yaml/api_steps.yml
I am adding various pipeline scenarios for bash util methods. They are mainly to test the state management which we are going to enhance.
=> Added various bash util cases for state

tests/yaml/S_Bash_Util_0013.yml, tests/yaml/S_Bash_Util_0014.yml, tests/yaml/S_Bash_Util_0015.yml, tests/yaml/S_Bash_Util_0016.yml, tests/yaml/S_Bash_Util_0017.yml
Based on earlier created yamls, just removing redundant inputResources
=> Removing redundant inputResources

tests/yaml/MB_G_001.yml, tests/yaml/MB_G_002.yml, tests/yaml/MB_G_004.yml, tests/yaml/MB_G_005.yml, tests/yaml/MB_G_007.yml
YML files for multiple pipeline source tests.
=> PIPE-2997 - Adds YML files to test multiple pipeline sources.

tests/yaml/S_Bash_Util_0018.yml
New yaml is added that uploads 200MB of file to artifactory and then downloads the same.
=> PIPE-3555: Added yaml to add 200MB of file to artifactory and downlaod the same

tests/yaml/S_PS_UTIL_0072.yml
A pipeline to upload/download 1GB from/to artifactory
=> PIPE-3555: Test to upload/download 1GB to/from artifactory

tests/yaml/N_DyNodeK8s_A_0008.yml, tests/yaml/N_DyNodeK8s_A_0009.yml, tests/yaml/S_Bash_0539.yml, tests/yaml/S_Bash_0540.yml, tests/yaml/S_Bash_0541.yml, tests/yaml/S_PS_R_FLSPEC_0018.yml
take arguments in json format for the aql in filespec resource
=> FileSpec with AQL

tests/yaml/S_CreateReleaseBundle_0002.yml, tests/yaml/S_CreateReleaseBundle_0003.yml, tests/yaml/S_CreateReleaseBundle_0004.yml, tests/yaml/S_PublishBuildInfo_0002.yml, tests/yaml/S_PublishBuildInfo_0003.yml, tests/yaml/S_PublishBuildInfo_0004.yml, tests/yaml/S_SignReleaseBundle_0002.yml, tests/yaml/S_SignReleaseBundle_0003.yml, tests/yaml/S_SignReleaseBundle_0004.yml, tests/yaml/S_SignReleaseBundle_0005.yml, tests/yaml/S_SignReleaseBundle_0006.yml, tests/yaml/S_XrayScan_0002.yml, tests/yaml/S_XrayScan_0003.yml, tests/yaml/S_XrayScan_0004.yml, tests/yaml/S_XrayScan_0005.yml, tests/yaml/S_XrayScan_0006.yml
Adds YML files for new tests related to increasing the number of resource and integration types allowed in native steps that are not typically used by those steps.
=> Adds expanded allowed inputs YMLs.

tests/yaml/S_B_Jen_0027.yml
Updates the integration name to work as an automated test.
=> Changes integration name in S_B_Jen_0027.

tests/yaml/S_Bash_0540.yml, tests/yaml/S_Bash_0541.yml, tests/yaml/S_Bash_0542.yml, tests/yaml/S_PS_Language_0017.yml
This the previous PR for this feature was missing bash steps.
=> feature-PIPE-2674 Add missing yml bash steps.

tests/yaml/S_WF_016.yml, tests/yaml/S_WF_017.yml, tests/yaml/S_WF_018.yml, tests/yaml/S_WF_019.yml, tests/yaml/S_WF_020.yml, tests/yaml/S_WF_021.yml, tests/yaml/S_WF_022.yml, tests/yaml/S_WF_023.yml, tests/yaml/S_WF_024.yml, tests/yaml/S_WF_025.yml, tests/yaml/S_WF_026.yml, tests/yaml/S_WF_027.yml, tests/yaml/S_WF_028.yml, tests/yaml/S_WF_029.yml, tests/yaml/S_WF_030.yml, tests/yaml/S_WF_031.yml, tests/yaml/S_WF_032.yml, tests/yaml/S_WF_033.yml
* Added automations for Linux nodes.
* Added automations for Windows nodes.
=> Added YAMLs for PIPE-3850

tests/yaml/S_Matrix_MN_001.yml, tests/yaml/S_Matrix_MN_002.yml, tests/yaml/S_Matrix_MN_003.yml, tests/yaml/S_Matrix_MN_004.yml, tests/yaml/S_Matrix_MN_005.yml, tests/yaml/S_Matrix_MN_006.yml, tests/yaml/S_Matrix_MN_007.yml, tests/yaml/S_Matrix_MN_008.yml, tests/yaml/S_Matrix_MN_009.yml
* Added automation yaml files for the story.
* Contains two yaml which now can be tested manually but in future might try to automate - `S_Matrix_MN_008` & `S_Matrix_MN_009`
=> Added yaml files for multi node matrix automation

tests/yaml/N_DyNodeAWS_0074.yml, tests/yaml/N_DyNodeAWS_0075.yml, tests/yaml/N_DyNodeAWS_0076.yml, tests/yaml/N_DyNodeAWS_0077.yml, tests/yaml/N_DyNodeAzure_0039.yml, tests/yaml/N_DyNodeAzure_0040.yml, tests/yaml/N_DyNodeAzure_0041.yml, tests/yaml/N_DyNodeAzure_0042.yml, tests/yaml/N_DyNodeGCP_0042.yml, tests/yaml/N_DyNodeGCP_0043.yml, tests/yaml/N_DyNodeGCP_0044.yml, tests/yaml/N_DyNodeK8s_A_0010.yml, tests/yaml/N_DyNodeK8s_A_0011.yml, tests/yaml/N_DyNodeK8s_A_0012.yml
=> PIPE-3226 Test for insecure registries entries

tests/yaml/values/correct/values.yml
DockerBuildAndPush automation case
=> DockerBuildAndPush automation case

tests/yaml/Environments_WF_001.yml, tests/yaml/Environments_WF_002.yml, tests/yaml/Environments_WF_003.yml, tests/yaml/Environments_WF_004.yml, tests/yaml/Environments_WF_005.yml, tests/yaml/Environments_WF_006.yml, tests/yaml/Environments_WF_007.yml, tests/yaml/Environments_WF_008.yml
=> YML files for projects with environments

tests/yaml/A_passthrough.yml
YML for passthrough pipelineSource permissions.
=> Adds YML for passthrough tests.

tests/yaml/S_WF_025.yml, tests/yaml/S_WF_026.yml, tests/yaml/S_WF_027.yml, tests/yaml/S_WF_028.yml, tests/yaml/S_WF_029.yml, tests/yaml/S_WF_030.yml, tests/yaml/S_WF_031.yml, tests/yaml/S_WF_032.yml, tests/yaml/S_WF_033.yml
Apologies for the incorrect YAMLs 🤦🏼 
Adding screenshot of their validation -
=> Fixed the powershell scripts for step workflow

tests/yaml/S_WF_039.yml, tests/yaml/S_WF_040.yml
Tests for chronological steps.  First that the an individual step will run one at a time and then that in a pipeline with multiple steps, the steps do not wait for the other chronological step in another run.
=> Adds new chronological step tests.

tests/yaml/WH_generic_0001.yml
Adding WH_generic_0001 for PIPE-4339
=> Adding WH_generic_0001 for PIPE-4339

tests/yaml/A_PipelineSources_0080.yml
One new YML file for the new test case.
=> Adds YML for A-PipelineSources-0080.

tests/yaml/S_Bash_Util_0019.yml, tests/yaml/S_Bash_Util_0020.yml, tests/yaml/S_Bash_Util_0021.yml, tests/yaml/S_Bash_Util_0022.yml, tests/yaml/S_PS_UTIL_0073.yml, tests/yaml/S_PS_UTIL_0074.yml, tests/yaml/S_PS_UTIL_0075.yml, tests/yaml/S_PS_UTIL_0076.yml
YML for eight new write_output test cases.
=> PIPE-4961 - Additional write_output test cases YMLs.

tests/yaml/S_Bash_0575.yml, tests/yaml/S_Bash_0576.yml, tests/yaml/S_PS_I_pagerduty_0001.yml, tests/yaml/S_PS_I_pagerduty_0002.yml
new yaml for use with pagerduty integration automation
=> automation for pagerduty integration

tests/yaml/P_Pipelines_0063.yml
Adds P_Pipelines_0063 to test resource update from another pipeline with a dependencyMode configured when a step using the resource is not first.
=> Adds P_Pipelines_0063

tests/yaml/P_Pipelines_0064.yml, tests/yaml/P_Pipelines_0065.yml
Sorry, I had completely forgotten I had these.  Moves 63 to 65 and adds pipelines 63 and 64.
=> PIPE-4029 - Pipeline retention policy.

tests/yaml/S_HelmDeploy_0008.yml, tests/yaml/S_HelmDeploy_0013.yml, tests/yaml/S_HelmDeploy_0014.yml, tests/yaml/S_HelmDeploy_0015.yml, tests/yaml/S_HelmDeploy_0016.yml
=> PIPE-4819 - automation PR fixes

tests/yaml/A-Steplets-0055.yml, tests/yaml/A-Steps-0101.yml
Tests to confirm that logup is uploading consoles.
=> Logup tests.

tests/yaml/S_HelmDeploy_0033.yml, tests/yaml/S_HelmDeploy_0034.yml, tests/yaml/S_HelmDeploy_0035.yml, tests/yaml/S_HelmDeploy_0036.yml, tests/yaml/S_HelmDeploy_0037.yml, tests/yaml/S_PS_HelmDeploy_0013.yml
=> PIPE-5543 - add ymls

tests/yaml/S_PromoteBuild_0018.yml, tests/yaml/S_PromoteBuild_0019.yml, tests/yaml/S_PromoteBuild_0020.yml, tests/yaml/S_PromoteBuild_0021.yml
when pipeInfo verification fails.
=> PIPE-5768 Tests for failing PromoteBuild

tests/yaml/S_Bash_0577.yml, tests/yaml/S_Bash_0578.yml
https://jira.jfrog.org/browse/PIPE-5858
=> Conditional execution of a step, depending on previous step’s status

tests/yaml/S_WF_6266_001.yml, tests/yaml/S_WF_6266_002.yml, tests/yaml/S_WF_6266_003.yml
updated YAMLS for the PIPE-6266 ticket
=> PIPE-6266 - step timeout default

tests/yaml/WH_BBS_PR_5167_0001.yml
YAML file for PIPE-5167's automation
=> PIPE-5167 - Update bitbucket webhook to trigger pull requests when source branch updated

tests/yaml/S-Matrix-6230-0001.yml
1. Update yml file to remove "-" (dash)
2. Added default node pool for steps
=> PIPE-6230 Update S-Matrix-6230-0001.yml

tests/yaml/R_GitRepo_5961_001.yml
Multiple test cases in one YML file because of the setup required to run these, which they can all share.
=> PIPE-5961 - Pull request branch filters.

tests/yaml/A_Templates_6971.yml
Pushes tags for template releases.
=> Push template releases.

tests/values/gitRepoValues.yml, tests/yaml/A-TemplateSync-6731-001.yml, tests/yaml/A-TemplateSync-6731-002.yml, tests/yaml/A-TemplateSync-6731-003.yml, tests/yaml/A-TemplateSync-6731-004.yml, tests/yaml/A-TemplateSync-6731-005.yml, tests/yaml/A-TemplateSync-6731-006.yml, tests/yaml/A-TemplateSync-6731-007.yml, tests/yaml/A-TemplateSync-6731-008.yml
Steps to push commits to a template repo.  The repository locations will need to be updated in `gitRepoValues.yml`.
=> PIPE-6731 - Update templates.

tests/yaml/P_WF_7379_001.yml, tests/yaml/P_WF_7379_002.yml
Two more test cases.  Simple pipelines with one resource each.
=> PIPE-7379 - Test cases for triggering resource versions.

tests/yaml/A_Search_Pipelines_6594_0001.yml, tests/yaml/A_Search_Pipelines_6594_0004.yml, tests/yaml/A_Search_Pipelines_6594_0020.yml, tests/yaml/A_Search_Pipelines_6594_0021.yml, tests/yaml/A_Search_Pipelines_6594_0026.yml, tests/yaml/A_Search_Pipelines_6594_0032.yml, tests/yaml/A_Search_Pipelines_6997_0001.yml, tests/yaml/A_Search_Pipelines_7252_0001.yml, tests/yaml/A_Search_Pipelines_7631_0001.yml
Add yamls for:
PIPE-6954
PIPE-6997
PIPE-7252
PIPE-6731
=> PIPE-7252 - add ymls for search api

tests/yaml/P_WF_7379_002.yml
Replacing the resource in that test case with twenty different resources, each triggering a different pipeline.
=> PIPE-7379 - Restructure P_WF_7379_002.

tests/yaml/S_WF_6393_001.yml, tests/yaml/S_WF_6393_002.yml, tests/yaml/S_WF_6393_003.yml, tests/yaml/S_WF_6393_004.yml, tests/yaml/S_WF_7289_001.yml, tests/yaml/S_WF_7289_002.yml
Found the missing PIPE-6393 YML files in an unmerged pull request and updated the node pool names to be unique.  And new tests for cancelling and timing out steps in conditional workflows.
=> PIPE-7289 - New conditional workflow test case.

tests/yaml/S_CWF_5858_0003.yml, tests/yaml/S_CWF_5858_0004.yml, tests/yaml/S_CWF_5858_0005.yml, tests/yaml/S_CWF_5858_0006.yml, tests/yaml/S_CWF_5858_0007.yml, tests/yaml/S_CWF_5858_0008.yml, tests/yaml/S_CWF_5858_0009.yml, tests/yaml/S_CWF_5858_0010.yml, tests/yaml/S_CWF_5858_0011.yml
https://jira.jfrog.org/browse/PIPE-7801
=> PIPE-7801 Add seperate files for each test case

tests/yaml/S_CWF_5858_0011.yml
https://jira.jfrog.org/browse/PIPE-7801
=> Update S_CWF_5858_0011.yml to use correct step name

tests/values/gitRepoValues.yml, tests/yaml/R_GitRepo_5961_001.yml
Pointing all the 5961 webhook cases to Org_test_Automation_Webhooks
=> PIPE-7727 - Webhooks

tests/yaml/N_DyNodeAWS_8302_001.yml, tests/yaml/N_DyNodeAWS_8302_002.yml, tests/yaml/N_DyNodeAWS_8302_003.yml, tests/yaml/N_DyNodeAWS_8302_005.yml, tests/yaml/N_DyNodeAWS_8302_006.yml, tests/yaml/N_DyNodeAWS_8302_007.yml, tests/yaml/N_DyNodeAWS_8302_008.yml, tests/yaml/N_DyNodeAWS_8302_010.yml, tests/yaml/N_K8NODES_GENERIC_8302_001.yml, tests/yaml/N_K8NODES_GENERIC_8302_002.yml, tests/yaml/P_Pipelines_8302_001.yml, tests/yaml/P_Pipelines_8302_002.yml, tests/yaml/P_Pipelines_8302_003.yml, tests/yaml/P_Pipelines_8302_004.yml, tests/yaml/P_Pipelines_8302_005.yml, tests/yaml/P_Pipelines_8302_006.yml, tests/yaml/P_Pipelines_8302_007.yml
Test cases checking JFrog CLI versions.
=> PIPE-8302 - Test cases for each operating system.

tests/PS-Sync-9494.yml, tests/yaml/A-Extension-0013.yml, tests/yaml/WH_DeleteBranch_8878.yml, tests/yaml/WH_DeleteBranch_8878_001.yml, tests/yaml/values/config/PS-Sync-9494.yml
Add file for delete scm deleted branch and for pipeline source changes
=> Add file for delete scm deleted branch and for pipeline source changes

tests/yaml/P_WF_10056_0001.yml, tests/yaml/P_WF_10056_0002.yml
=> PIPE-10056 tests for 500 error on retrigger with

pipe10892-1/.jfrog-pipelines/P_SYC_Pipelines_10158_002.yml, pipe10892-1/.jfrog-pipelines/cd-values.yml, pipe10892/.jfrog-pipelines/P_SYC_Pipelines_10158_002.yml, pipe10892/.jfrog-pipelines/cd-values.yml
Fix for sync silently ignoring bad files instead of failing
=> PIPE-10892 - Fix for sync silently ignoring bad files instead of failing

helmFile10390-1/.jfrog-pipelines/_helpers.tpl, helmFile10390-1/_helpers.tpl, helmFile10390-2/.jfrog-pipelines/.jfrog-pipelines/P_SYC_Pipelines_10390_file.yml, helmFile10390-2/.jfrog-pipelines/.jfrog-pipelines/_helpers.tpl, helmFile10390-2/.jfrog-pipelines/.jfrog-pipelines/config.yml, helmFile10390-2/.jfrog-pipelines/config.yml, helmFile10390/.jfrog-pipelines/P_SYC_Pipelines_10390_file.yml, template-10767/.jfrog-pipelines/A-Templates-10767-3.yml, template-10767/.jfrog-pipelines/A-Templates-10767.yml, template-10767/.jfrog-pipelines/devTemplate.yml, template-10767/.jfrog-pipelines/values.yml, tests/uploadTemplate/templates/jfrog/helmTemplate/readme.md, tests/uploadTemplate/templates/jfrog/helmTemplate/templateDefinition.yml, tests/uploadTemplate/templates/jfrog/helmTemplate/values.yml, tests/yaml/A-Templates-10390-1.yml, tests/yaml/A-Templates-10390.yml, tests/yaml/A-Templates-10767-1.yml, tests/yaml/A-Templates-10767-2.yml, tests/yaml/PS_Sync_10390_010.yml, tests/yaml/PS_Sync_10390_011.yml, tests/yaml/values/syncTemplate/helmPublishTemplate.yml, tests/yaml/values/values_10039.yml
Add helm new function support yaml 10390
=> Add helm new function support yaml 10390
